[package]
name = "android-position-estimator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
desktop = []

[[bin]]
name = "position_estimator"
path = "src/main.rs"
required-features = ["desktop"]

[lib]
name = "android_position_estimator"
crate_type=["cdylib", "lib"]

[dependencies]
bevy = "0.12.0"
log = "0.4.20"

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.10"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11.0"
